export let data = [

  {
    "id": "1",
    "title": "Learn JavaScript in 30 Minutes",
    "channelName": "Code With Harry",
    "views": "1.2M views",
    "uploadedAt": "2 weeks ago",
    "thumbnail": "https://img.youtube.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
    "duration": "30:12"
  },
  
  {
    "id": "2",
    "title": "React JS Full Course for Beginners",
    "channelName": "freeCodeCamp.org",
    "views": "5.8M views",
    "uploadedAt": "1 year ago",
    "thumbnail": "https://img.youtube.com/vi/bMknfKXIFA8/maxresdefault.jpg",
    "duration": "12:01:39"
  },
   {
    id: 30,
    title: "Building a Chat App with Socket.io",
    channel: "Realtime Web",
    views: "270K views",
    time: "5 months ago",
    thumbnail: "https://picsum.photos/seed/socket/640/360",
  },
  {
    "id": "3",
    "title": "Tailwind CSS Crash Course",
    "channelName": "Traversy Media",
    "views": "900K views",
    "uploadedAt": "8 months ago",
    "thumbnail": "https://img.youtube.com/vi/dFgzHOX84xQ/maxresdefault.jpg",
    "duration": "1:12:45"
  },
  {
    "id": "4",
    "title": "Node.js Express MongoDB CRUD App",
    "channelName": "JavaScript Mastery",
    "views": "620K views",
    "uploadedAt": "6 months ago",
    "thumbnail": "https://img.youtube.com/vi/7CqJlxBYj-M/maxresdefault.jpg",
    "duration": "2:45:10"
  },
  {
    "id": "5",
    "title": "HTML CSS Full Course",
    "channelName": "Apna College",
    "views": "3.4M views",
    "uploadedAt": "10 months ago",
    "thumbnail": "https://img.youtube.com/vi/HcOc7P5BMi4/maxresdefault.jpg",
    "duration": "7:30:22"
  },

  
  {
    id: 21,
    title: "Learn SvelteKit in 1 Hour",
    channel: "Svelte School",
    views: "55K views",
    time: "4 days ago",
    thumbnail: "https://picsum.photos/seed/svelte/640/360",
  },
  {
    id: 22,
    title: "AWS S3 & EC2 Tutorial",
    channel: "Cloud Guru",
    views: "780K views",
    time: "1 year ago",
    thumbnail: "https://picsum.photos/seed/aws/640/360",
  },
 
  { "id": "1", "title": "JavaScript Full Course", "channelName": "Code With Harry", "views": "1.2M views", "uploadedAt": "2 weeks ago", "duration": "6:30:00", "thumbnail": "https://img.youtube.com/vi/PkZNo7MFNFg/maxresdefault.jpg" },
  { "id": "2", "title": "React JS Crash Course", "channelName": "Traversy Media", "views": "900K views", "uploadedAt": "1 month ago", "duration": "1:48:00", "thumbnail": "https://img.youtube.com/vi/w7ejDZ8SWv8/maxresdefault.jpg" },
  { "id": "3", "title": "Node.js Tutorial", "channelName": "Programming with Mosh", "views": "2.1M views", "uploadedAt": "1 year ago", "duration": "1:20:00", "thumbnail": "https://img.youtube.com/vi/TlB_eWDSMt4/maxresdefault.jpg" },
   {
    id: 27,
    title: "Vim in 100 Seconds",
    channel: "Terminal Velocity",
    views: "330K views",
    time: "1 year ago",
    thumbnail: "https://picsum.photos/seed/vim/640/360",
  },
  {
    id: 28,
    title: "Testing React Apps with Jest",
    channel: "QA Engineers",
    views: "85K views",
    time: "3 months ago",
    thumbnail: "https://picsum.photos/seed/jest/640/360",
  },
  { "id": "4", "title": "MongoDB in One Video", "channelName": "Apna College", "views": "700K views", "uploadedAt": "3 months ago", "duration": "2:10:00", "thumbnail": "https://img.youtube.com/vi/rU9ZODw5yvU/maxresdefault.jpg" },
  { "id": "5", "title": "HTML CSS Full Course", "channelName": "freeCodeCamp.org", "views": "5M views", "uploadedAt": "2 years ago", "duration": "7:00:00", "thumbnail": "https://img.youtube.com/vi/mU6anWqZJcc/maxresdefault.jpg" },
  {
    id: 1,
    title: "React 18 Full Course for Beginners",
    channel: "Code Evolution",
    views: "1.2M views",
    time: "1 year ago",
    thumbnail: "https://picsum.photos/seed/react18/640/360",
  },
  {
    id: 2,
    title: "CSS Grid vs Flexbox: When to use which?",
    channel: "Frontend Mastery",
    views: "450K views",
    time: "2 months ago",
    thumbnail: "https://picsum.photos/seed/cssgrid/640/360",
  },
  {
    id: 3,
    title: "Build a Netflix Clone with Next.js 14",
    channel: "Dev Simplified",
    views: "890K views",
    time: "3 weeks ago",
    thumbnail: "https://picsum.photos/seed/netflix/640/360",
  },
  {
    id: 4,
    title: "TypeScript Crash Course 2024",
    channel: "Typed Code",
    views: "210K views",
    time: "5 days ago",
    thumbnail: "https://picsum.photos/seed/ts/640/360",
  },
  { "id": "6", "title": "Tailwind CSS Tutorial", "channelName": "Net Ninja", "views": "450K views", "uploadedAt": "5 months ago", "duration": "1:15:00", "thumbnail": "https://img.youtube.com/vi/UBOj6rqRUME/maxresdefault.jpg" },
  { "id": "7", "title": "Express JS Crash Course", "channelName": "Traversy Media", "views": "800K views", "uploadedAt": "8 months ago", "duration": "1:00:00", "thumbnail": "https://img.youtube.com/vi/L72fhGm1tfE/maxresdefault.jpg" },
  { "id": "8", "title": "Git and GitHub Tutorial", "channelName": "CodeWithHarry", "views": "1.8M views", "uploadedAt": "1 year ago", "duration": "2:30:00", "thumbnail": "https://img.youtube.com/vi/gwWKnnCMQ5c/maxresdefault.jpg" },
    {
    id: 29,
    title: "SQL vs NoSQL Explained",
    channel: "Data Decisions",
    views: "440K views",
    time: "2 years ago",
    thumbnail: "https://picsum.photos/seed/sqlnosql/640/360",
  },
  { "id": "9", "title": "JavaScript Projects", "channelName": "JavaScript Mastery", "views": "600K views", "uploadedAt": "4 months ago", "duration": "3:40:00", "thumbnail": "https://img.youtube.com/vi/Zi-Q0t4gMC8/maxresdefault.jpg" },
  { "id": "10", "title": "React Portfolio Project", "channelName": "JavaScript Mastery", "views": "520K views", "uploadedAt": "6 months ago", "duration": "2:50:00", "thumbnail": "https://img.youtube.com/vi/0h2b4ftbZcU/maxresdefault.jpg" },
  {
    id: 5,
    title: "Docker Explained in 100 Seconds",
    channel: "Fireship",
    views: "2.5M views",
    time: "1 year ago",
    thumbnail: "https://picsum.photos/seed/docker/640/360",
  },
  {
    id: 6,
    title: "Learn Tailwind CSS - Modern Styling",
    channel: "Design to Code",
    views: "120K views",
    time: "4 days ago",
    thumbnail: "https://picsum.photos/seed/tailwind/640/360",
  },
  {
    id: 7,
    title: "Node.js & Express API Tutorial",
    channel: "Backend Basic",
    views: "340K views",
    time: "6 months ago",
    thumbnail: "https://picsum.photos/seed/node/640/360",
  },
  {
    id: 8,
    title: "Understanding Async Await in JavaScript",
    channel: "JS Daily",
    views: "67K views",
    time: "2 weeks ago",
    thumbnail: "https://picsum.photos/seed/async/640/360",
  },
  { "id": "11", "title": "CSS Animations", "channelName": "Kevin Powell", "views": "300K views", "uploadedAt": "9 months ago", "duration": "45:00", "thumbnail": "https://img.youtube.com/vi/YszONjKpgg4/maxresdefault.jpg" },
  { "id": "12", "title": "Redux Toolkit Tutorial", "channelName": "Codevolution", "views": "400K views", "uploadedAt": "1 year ago", "duration": "1:30:00", "thumbnail": "https://img.youtube.com/vi/9zySeP5vH9c/maxresdefault.jpg" },
  { "id": "13", "title": "Next.js Full Course", "channelName": "freeCodeCamp.org", "views": "1.1M views", "uploadedAt": "8 months ago", "duration": "5:10:00", "thumbnail": "https://img.youtube.com/vi/mTz0GXj8NN0/maxresdefault.jpg" },
  { "id": "14", "title": "API in JavaScript", "channelName": "Thapa Technical", "views": "350K views", "uploadedAt": "7 months ago", "duration": "1:10:00", "thumbnail": "https://img.youtube.com/vi/h0ZUpPiV1ac/maxresdefault.jpg" },
  { "id": "15", "title": "TypeScript Basics", "channelName": "Academind", "views": "900K views", "uploadedAt": "1 year ago", "duration": "2:00:00", "thumbnail": "https://img.youtube.com/vi/BwuLxPH8IDs/maxresdefault.jpg" },
  {
    id: 9,
    title: "System Design Interview: Design Instagram",
    channel: "Tech Architecture",
    views: "1.8M views",
    time: "2 years ago",
    thumbnail: "https://picsum.photos/seed/sysdesign/640/360",
  },
  {
    id: 10,
    title: "Git & GitHub Crash Course",
    channel: "Version Control",
    views: "900K views",
    time: "8 months ago",
    thumbnail: "https://picsum.photos/seed/git/640/360",
  },
  {
    id: 11,
    title: "Python for Data Science - Full Course",
    channel: "Data Camp",
    views: "3.2M views",
    time: "3 years ago",
    thumbnail: "https://picsum.photos/seed/python/640/360",
  },
  {
    id: 12,
    title: "Figma to HTML/CSS Conversion",
    channel: "UI/UX Labs",
    views: "150K views",
    time: "1 month ago",
    thumbnail: "https://picsum.photos/seed/figma/640/360",
  },
  { "id": "16", "title": "Frontend Roadmap", "channelName": "Fireship", "views": "2.5M views", "uploadedAt": "1 year ago", "duration": "10:00", "thumbnail": "https://img.youtube.com/vi/zJSY8tbf_ys/maxresdefault.jpg" },
  { "id": "17", "title": "Backend Roadmap", "channelName": "Fireship", "views": "1.9M views", "uploadedAt": "1 year ago", "duration": "12:00", "thumbnail": "https://img.youtube.com/vi/XBu54nfzxAQ/maxresdefault.jpg" },
  { "id": "18", "title": "System Design Basics", "channelName": "Gaurav Sen", "views": "1.3M views", "uploadedAt": "2 years ago", "duration": "50:00", "thumbnail": "https://img.youtube.com/vi/UzLMhqg3_Wc/maxresdefault.jpg" },
  { "id": "19", "title": "Data Structures JS", "channelName": "freeCodeCamp.org", "views": "2M views", "uploadedAt": "3 years ago", "duration": "8:00:00", "thumbnail": "https://img.youtube.com/vi/t2CEgPsws3U/maxresdefault.jpg" },
  { "id": "20", "title": "Async JS Explained", "channelName": "Akshay Saini", "views": "1.4M views", "uploadedAt": "1 year ago", "duration": "1:00:00", "thumbnail": "https://img.youtube.com/vi/PoRJizFvM7s/maxresdefault.jpg" },
  {
    id: 13,
    title: "Redux Toolkit - State Management",
    channel: "Redux Wizard",
    views: "80K views",
    time: "3 days ago",
    thumbnail: "https://picsum.photos/seed/redux/640/360",
  },
  {
    id: 14,
    title: "Web Accessibility (A11y) Guide",
    channel: "Inclusive Web",
    views: "45K views",
    time: "5 months ago",
    thumbnail: "https://picsum.photos/seed/a11y/640/360",
  },
  {
    id: 15,
    title: "VS Code Extensions You Need",
    channel: "Productivity Pro",
    views: "500K views",
    time: "1 week ago",
    thumbnail: "https://picsum.photos/seed/vscode/640/360",
  },
  {
    id: 16,
    title: "Day in the Life of a Software Engineer",
    channel: "Tech Vlogs",
    views: "4.5M views",
    time: "4 years ago",
    thumbnail: "https://picsum.photos/seed/daylife/640/360",
  },
  { "id": "21", "title": "JavaScript Interview Questions", "channelName": "Namaste JavaScript", "views": "800K views", "uploadedAt": "10 months ago", "duration": "40:00", "thumbnail": "https://img.youtube.com/vi/pN6jk0uUrD8/maxresdefault.jpg" },
  { "id": "22", "title": "CSS Flexbox Guide", "channelName": "Web Dev Simplified", "views": "600K views", "uploadedAt": "1 year ago", "duration": "30:00", "thumbnail": "https://img.youtube.com/vi/fYq5PXgSsbE/maxresdefault.jpg" },
  { "id": "23", "title": "CSS Grid Tutorial", "channelName": "Web Dev Simplified", "views": "550K views", "uploadedAt": "1 year ago", "duration": "35:00", "thumbnail": "https://img.youtube.com/vi/rg7Fvvl3taU/maxresdefault.jpg" },
  { "id": "24", "title": "REST API Explained", "channelName": "Academind", "views": "700K views", "uploadedAt": "2 years ago", "duration": "25:00", "thumbnail": "https://img.youtube.com/vi/7YcW25PHnAA/maxresdefault.jpg" },
  { "id": "25", "title": "JWT Authentication", "channelName": "Web Dev Simplified", "views": "620K views", "uploadedAt": "2 years ago", "duration": "20:00", "thumbnail": "https://img.youtube.com/vi/mbsmsi7l3r4/maxresdefault.jpg" },
  {
    id: 17,
    title: "MongoDB Crash Course",
    channel: "Database Dojo",
    views: "230K views",
    time: "9 months ago",
    thumbnail: "https://picsum.photos/seed/mongo/640/360",
  },
  {
    id: 18,
    title: "GraphQL vs REST API",
    channel: "API Central",
    views: "110K views",
    time: "2 months ago",
    thumbnail: "https://picsum.photos/seed/graphql/640/360",
  },
  {
    id: 19,
    title: "Rust vs Go - Which one to learn?",
    channel: "Lang War",
    views: "600K views",
    time: "1 year ago",
    thumbnail: "https://picsum.photos/seed/rustgo/640/360",
  },
  {
    id: 20,
    title: "Portfolio Review: Roast My Code",
    channel: "Senior Dev",
    views: "300K views",
    time: "2 weeks ago",
    thumbnail: "https://picsum.photos/seed/portfolio/640/360",
  },
  { "id": "26", "title": "Build MERN App", "channelName": "JavaScript Mastery", "views": "980K views", "uploadedAt": "6 months ago", "duration": "4:30:00", "thumbnail": "https://img.youtube.com/vi/ngc9gnGgUdA/maxresdefault.jpg" },
  { "id": "27", "title": "VS Code Tips", "channelName": "Fireship", "views": "1.1M views", "uploadedAt": "1 year ago", "duration": "8:00", "thumbnail": "https://img.youtube.com/vi/ifTF3ags0XI/maxresdefault.jpg" },
  { "id": "28", "title": "Web Dev Tools", "channelName": "Fireship", "views": "900K views", "uploadedAt": "11 months ago", "duration": "9:00", "thumbnail": "https://img.youtube.com/vi/JzQKp9ZzZzY/maxresdefault.jpg" },
  { "id": "29", "title": "Responsive Design", "channelName": "Kevin Powell", "views": "480K views", "uploadedAt": "1 year ago", "duration": "50:00", "thumbnail": "https://img.youtube.com/vi/srvUrASNj0s/maxresdefault.jpg" },
  { "id": "30", "title": "Web Performance Tips", "channelName": "Google Chrome Developers", "views": "650K views", "uploadedAt": "2 years ago", "duration": "45:00", "thumbnail": "https://img.youtube.com/vi/0fONene3OIA/maxresdefault.jpg" },
  {
    id: 23,
    title: "Clean Code Principles",
    channel: "Software Craft",
    views: "1.1M views",
    time: "3 years ago",
    thumbnail: "https://picsum.photos/seed/clean/640/360",
  },
  {
    id: 24,
    title: "Cybersecurity Basics for Beginners",
    channel: "Secured Life",
    views: "95K views",
    time: "2 months ago",
    thumbnail: "https://picsum.photos/seed/security/640/360",
  },
  {
    id: 25,
    title: "Machine Learning with JavaScript",
    channel: "AI Edge",
    views: "40K views",
    time: "1 week ago",
    thumbnail: "https://picsum.photos/seed/mljs/640/360",
  },
  {
    id: 26,
    title: "Cookies vs LocalStorage vs Session",
    channel: "Web Storage",
    views: "190K views",
    time: "6 months ago",
    thumbnail: "https://picsum.photos/seed/cookies/640/360",
  },
]